# -*- encoding: utf-8 -*-

=begin
# Ulama.io API

Ulama auto generated APIs

OpenAPI spec version: 0.1
Contact: support@ulama.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.55
=end

$:.push File.expand_path("../lib", __FILE__)
require "ulama-api/version"

Gem::Specification.new do |s|
  s.name        = "ulama-api"
  s.version     = UlamaApi::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Swagger-Codegen", "Marco"]
  s.email       = ["support@ulama.io", "marco@bon.so"]
  s.homepage    = "https://github.com/adamax-academy/ulama-api"
  s.summary     = "Ulama.io API Ruby Gem"
  s.description = "Ulama API"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
