=begin
#Ulama.io API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.1
Contact: support@ulama.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.55
=end

# Common files
require 'ulama-api/api_client'
require 'ulama-api/api_error'
require 'ulama-api/version'
require 'ulama-api/configuration'

# Models
require 'ulama-api/models/abandon'
require 'ulama-api/models/admin'
require 'ulama-api/models/authoirize'
require 'ulama-api/models/carts'
require 'ulama-api/models/enroll_body'
require 'ulama-api/models/orders'
require 'ulama-api/models/orders_extra'
require 'ulama-api/models/orders_items'
require 'ulama-api/models/payments'
require 'ulama-api/models/products'
require 'ulama-api/models/products_language'
require 'ulama-api/models/suspend_body'
require 'ulama-api/models/user'
require 'ulama-api/models/users_body'
require 'ulama-api/models/users_percentage'
require 'ulama-api/models/websited'

# APIs
require 'ulama-api/api/default_api'

module UlamaApi
  class << self
    # Customize default settings for the SDK using block.
    #   UlamaApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
